[package]
name = "CRATE_NAME"
version = "0.1.0"
authors = ["AUTHOR"]
description = "CRATE_DESCRIPTION"

#  intentionally left blank
[dependencies]
hyper = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
error-chain = "0.10"
